apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sb.fullname" . }}-data
  labels:
    {{- include "sb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
