version: "3.7"

services:
  db:
    # container_name: sql-db
    build:
      context: sm-db
      dockerfile: Dockerfile
    image: sm-db
    cap_add:
      - SYS_NICE #
    # use the old authentication protocol, so I can use the popular mysql nodejs package
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'profile'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'password!'
    ports:
      - 3308:3306
    volumes:
      - data:/var/lib/mysql
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./sm-api/db:/db
    # db cred can be hidden in secrets and other places.
    command: [ "-path", "/db/migrations", "-database",  "mysql://docker:password!@tcp(db)/profile?parseTime=true", "up" ]
  api:
    hostname: app
    restart: unless-stopped
    image: sm-api
    depends_on:
      - db
    build:
      context: sm-api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - type: bind
        source: ./sm-api
        target: /home/app
    working_dir: /home/app
    environment:
      PATH_TO_CONFIG: /home/app/config
    ports:
      - "8080:8080"
  ui:
    depends_on:
      - db
    image: sm-ui
    build:
      context: ./ui
      dockerfile: docker/Dockerfile
      target: dev
    ports:
      - "4201:4200"
    volumes:
      - ./ui:/app
volumes:
  data: {}
