version: "3.8"

services:
  db:
    platform: linux/arm64
    image: sm-db-arm64
  api:
    image: sm-api-arm64
    platform: linux/arm64
  ui:
    image: sm-ui-arm64
    platform: linux/arm64
  migrator:
    image: sm-api-arm64
    platform: linux/arm64
