version: "3.8"

services:
  db:
    build:
      context: db
    image: sm-db
    cap_add:
      - SYS_NICE
    # use the old authentication protocol, so I can use the popular mysql nodejs package
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'profile'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'password!'
    ports:
      - "3308:3306"
    volumes:
      - data:/var/lib/mysql
  api:
    hostname: app
    restart: unless-stopped
    image: sm-api
    depends_on:
      - db
    build:
      context: api
      target: dev
    volumes:
      - ./api:/home/app
    working_dir: /home/app
    environment:
      PATH_TO_CONFIG: /home/app/config
    ports:
      - "8080:8080"
  migrator:
    image: sm-api
    depends_on:
      - db
    build:
      context: api
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./api:/home/app
      - ./misc:/misc
    working_dir: /home/app
    environment:
      PATH_TO_CONFIG: /home/app/config
      MIGRATOR: 'true'
    command: >
      sh -c "/misc/wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  ui:
    depends_on:
      - db
    image: sm-ui
    build:
      context: ./ui
      target: dev
    ports:
      - "4201:4200"
    volumes:
      - ./ui:/app
volumes:
  data: {}
