version: "3.9"

services:
  api:
    build:
      context: sm-api
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./config:/app/config
      - ./db:/app/db
    environment:
      GIN_MODE: release
      PATH_TO_CONFIG: /app/config
  ui:
    build:
      context: ./ui
      dockerfile: docker/Dockerfile
      target: prod
    ports:
      - "8082:80"