apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sb-stack.fullname" . }}-pv
  labels:
    {{- include "sb-stack.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    # a different iscsi storage server at nfs.my.home configured
    targetPortal: 192.168.1.33:3260
    iqn: iqn.2021-06.my.home:lun1
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: false
    chapAuthSession: true
    secretRef:
      name: {{ include "sb-stack.name" . }}-chap-secret