apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sb-stack.fullname" . }}-data
  labels:
    {{- include "sb-stack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
