apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sb-stack.name" . }}-secret
data:
  MYSQL_USER_PWD: {{ .Values.db.cred.MYSQL_USER_PWD | b64enc }}
  MYSQL_ROOT_PWD: {{ .Values.db.cred.MYSQL_ROOT_PWD | b64enc }}