apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sb.fullname" . }}-api
  labels:
    {{- include "sb.labels" . | nindent 4 }}
    app: {{ template "sb.name" . }}-api
spec:
{{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "sb.name" . }}-api
  template:
    metadata:
    {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sb.labels" . | nindent 8 }}
        app: {{ template "sb.name" . }}-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "{{ .Chart.Name }}-init"
          image: "{{ .Values.wait.image.repository }}:{{ .Values.wait.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wait.image.pullPolicy }}
          args:
            - "job"
            - {{ printf "%s-migration-job" (include "sb.fullname" .) | quote }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: GIN_MODE
              value: release
            - name: PATH_TO_CONFIG
              value: /app/config
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/app/config"
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "sb.fullname" . }}-config
            items:
            - key: "sm.yaml"
              path: "sm.yaml"