apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sb.fullname" . }}-ui
  labels:
    {{- include "sb.labels" . | nindent 4 }}
    app: {{ template "sb.name" . }}-ui
spec:
{{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "sb.name" . }}-ui
  template:
    metadata:
    {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sb.labels" . | nindent 8 }}
        app: {{ template "sb.name" . }}-ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}