apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sb-stack.fullname" . }}-config
data:
  invoice.yaml: |
    DSN="{{ .Values.db.profile.user}}:{{ .Values.db.cred.MYSQL_USER_PWD }}@tcp(db)/{{ .Values.db.profile.database }}?parseTime=true"
    API_KEY="key"
    BASE_URL="http://localhost:8080"
    SERVER_PORT=8080
