apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sb-stack.fullname" . }}-migration-job
  labels:
    {{- include "sb-stack.labels" . | nindent 4 }}
    app: {{ template "sb-stack.name" . }}-migration-job
spec:
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sb-stack.labels" . | nindent 8 }}
        app: {{ template "sb-stack.name" . }}-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sb-stack.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          command:
            - "/bin/sh"
            - "-c"
            - |
            - git clone --single-branch --branch master
            - https://bdarge:$GIT_TOKEN@github.com/bdarge/small-business.git && ls -al small-business/sm-api/db && ls -l /app/config
          env:
            - name: MIGRATOR
              value: "true"
            - name: PATH_TO_CONFIG
              value: app/config
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sb-stack.name" . }}-secret
                  key: GIT_TOKEN
          volumeMounts:
            - name: migration-config
              mountPath: "/app/config"
      volumes:
        - name: migration-config
          configMap:
            name: {{ include "sb-stack.fullname" . }}-config
            items:
            - key: "sm.yaml"
              path: "sm.yaml"
      restartPolicy: {{ .Values.migration.job.restartPolicy }}