apiVersion: v1
kind: Service
metadata:
  name: {{ include "sb-stack.fullname" . }}-api-svc
  labels:
    {{- include "sb-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.api.service.targetPort }}
  selector:
    app: {{ template "sb-stack.name" . }}-api
    release: {{ $.Release.Name | quote }}
