name: CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]

env:
  REGISTRY: registry.gitlab.com/d6908/k8s
  IMAGE_NAME: sb-ui
  SB_API_BASE_URL: http://sb-info.my.home/api/v1
  ENV: PROD
   
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GL_REGISTRY }}
 
      - name: Build & Push Docker Images
        env:
          DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make
